### ISSUE TITLE
Error in `Load_Resize_and_Save_Stack` in python 3

### ISSUE THREAD

**Issue by gtrancourt** [gtrancourt/microCT-leaf-traits#1]
```
Traceback (most recent call last):
  File "/home/gtrancourt/Dropbox/_github/microCT-leaf-traits/Leaf_Segmentation_py3.py", line 101, in <module>
    gridrec_stack = Load_Resize_and_Save_Stack(filepath, grid_name, rescale_factor)
  File "/home/gtrancourt/Dropbox/_github/microCT-leaf-traits/Leaf_Segmentation_Functions_py3.py", line 1024, in Load_Resize_and_Save_Stack
    stack_rs = np.empty(np.array(stack.shape)/np.array([1, rescale_factor, rescale_factor]))
TypeError: 'numpy.float64' object cannot be interpreted as an integer
```

**Comment by gtrancourt** [comment]
The line that worked in python2 but caused conflict in python3 was:
```python
stack_rs = np.empty(np.array(stack.shape)/np.array([1, rescale_factor, rescale_factor]))
```

Corrected by converted type to `int64` here:
```python
resized_shape = np.array(stack.shape)/np.array([1, rescale_factor, rescale_factor])
        stack_rs = np.empty(shape = resized_shape.astype(np.int64))
```
